version: '2'

services:
  app:
    image: 'imshashikumar01/user-service:0.0.1'
    build:
      context: .
    container_name: app
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/sbibank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  database:
    image: 'postgres:13.1-alpine'
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sbibank
      - PGDATA=/data/postgres
